@tenantId = <your_tenant_id>
@providerAppId = <app_id_provider_app_registration>
@consumerAppId = <app_id_consumer_app_registration>
@consumerSecret = <password_consumer_app_registration>
@apimName = <api_management_name>
@apiPath = <api_path>

### Get Token for consumer
# @name consumerToken

POST https://login.microsoftonline.com/{{tenantId}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{consumerAppId}}
&resource={{providerAppId}}
&client_secret={{consumerSecret}}
&grant_type=client_credentials

#### Get Token Response
@accessToken = {{consumerToken.response.body.$.access_token}}

### Test get endpoint
GET https://{{apimName}}.azure-api.net/{{apiPath}}/get
Authorization: Bearer {{accessToken}}

### Test post endpoint (this should fail for reader, but not for the writer consumer)
POST https://{{apimName}}.azure-api.net/{{apiPath}}/post
Authorization: Bearer {{accessToken}}

### Get - No Token provided (this should always fail)
GET https://{{apimName}}.azure-api.net/{{apiPath}}/get

### Post - No Token provided (this should always fail)
GET https://{{apimName}}.azure-api.net/{{apiPath}}/post